name       : nomacs
version    : '3.12.0'
release    : 9
source     :
    - https://github.com/nomacs/nomacs/archive/3.12.tar.gz : f4a32169e6c0cb939971da2732e4d67c6e2e649506da1b55bfc94963a26280ff
    #- git|https://github.com/nomacs/nomacs-plugins.git : 3.12.0
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : nomacs is a free, open source image viewer
description: |
    nomacs is a free, open source image viewer that features several image manipulation tools and metadata support
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libcurl)
    - pkgconfig(libraw)
    - pkgconfig(libssh)
    - pkgconfig(libtiff-4)
    - pkgconfig(opencv)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - lcov
    - quazip-devel
rundeps    :
    - qt5-imageformats
setup      : |
    cd ImageLounge
    # Create the plugins directory in the source
    # But doesn't currently build with them included
    #cp -a $sources/nomacs-plugins.git plugins
    %cmake -DUSE_SYSTEM_QUAZIP=ON -DENABLE_TRANSLATIONS=ON .
build      : |
    %make -C ImageLounge
install    : |
    %make_install -C ImageLounge
