name       : nomacs
version    : 3.10.2
release    : 8
source     :
    - https://github.com/nomacs/nomacs/archive/3.10.2.tar.gz : ced900a1548be6fecef5d18e6ed5bdbc9b3eb749edf623c523327798a74a4ec0
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : nomacs is a free, open source image viewer
description: |
    nomacs is a free, open source image viewer that features several image manipulation tools and metadata support
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libcurl)
    - pkgconfig(libraw)
    - pkgconfig(libssh)
    - pkgconfig(libtiff-4)
    - pkgconfig(opencv)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - lcov
    - quazip-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Patch-for-quazip.patch

    cd ImageLounge
    sed -i "s|OPENCV_FOUND|OpenCV_FOUND|g" CMakeLists.txt
    %cmake -DUSE_SYSTEM_QUAZIP=ON -DENABLE_TRANSLATIONS=ON .
build      : |
    %make -C ImageLounge
install    : |
    %make_install -C ImageLounge
