name       : nomacs
version    : 3.6.1
release    : 2
source     :
    - https://github.com/nomacs/nomacs/archive/3.6.1.tar.gz : 09b289cac51a5fdccc02aa4a60405bbbd4b5bfdb6b2a52ca5b0cb3b0f7a87068
license    : GPL-3.0
component  : multimedia.graphics
summary    : nomacs is a free, open source image viewer
description: |
    nomacs is a free, open source image viewer that features several image manipulation tools and metadata support
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(libraw)
    - pkgconfig(libssh)
    - pkgconfig(libtiff-4)
    - pkgconfig(opencv)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - quazip-devel
setup      : |
    cd ImageLounge
    sed -i "s|OPENCV_FOUND|OpenCV_FOUND|g" CMakeLists.txt
    %cmake -DUSE_SYSTEM_QUAZIP=ON .
build      : |
    cd ImageLounge
    %make
install    : |
    cd ImageLounge
    %make_install
