name       : nomacs
version    : 3.8.0
release    : 6
source     :
    - https://github.com/nomacs/nomacs/archive/3.8.0.tar.gz : f43ad1507f2890db2fbaa0cb110de3ac5efe754cf2e7a053eaabfed4d5e06845
license    : GPL-3.0
component  : multimedia.graphics
summary    : nomacs is a free, open source image viewer
description: |
    nomacs is a free, open source image viewer that features several image manipulation tools and metadata support
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(libraw)
    - pkgconfig(libssh)
    - pkgconfig(libtiff-4)
    - pkgconfig(opencv)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - lcov
    - quazip-devel
setup      : |
    cd ImageLounge
    sed -i "s|OPENCV_FOUND|OpenCV_FOUND|g" CMakeLists.txt
    %cmake -DUSE_SYSTEM_QUAZIP=ON .
build      : |
    %make -C ImageLounge
install    : |
    %make_install -C ImageLounge
